FROM hasura/graphql-engine:v2.30.1.cli-migrations-v3

COPY ./hasura/migrations /hasura-migrations
COPY ./hasura/metadata /hasura-metadata

ENV HASURA_GRAPHQL_ENABLE_CONSOLE ${HASURA_GRAPHQL_ENABLE_CONSOLE}
ENV HASURA_GRAPHQL_ENABLED_LOG_TYPES ${HASURA_GRAPHQL_ENABLED_LOG_TYPES}
ENV HASURA_GRAPHQL_ENABLE_TELEMETRY ${HASURA_GRAPHQL_ENABLE_TELEMETRY}
ENV HASURA_GRAPHQL_LOG_LEVEL ${HASURA_GRAPHQL_LOG_LEVEL}
ENV HASURA_GRAPHQL_DEV_MODE ${HASURA_GRAPHQL_DEV_MODE}
ENV HASURA_GRAPHQL_DATABASE_URL ${HASURA_GRAPHQL_DATABASE_URL}
ENV HASURA_GRAPHQL_ADMIN_SECRET ${HASURA_GRAPHQL_ADMIN_SECRET}
ENV HASURA_GRAPHQL_JWT_SECRET ${HASURA_GRAPHQL_JWT_SECRET}
ENV HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT ${HASURA_GRAPHQL_MIGRATIONS_SERVER_TIMEOUT}
ENV ACTION_CONTROLLER_URL ${ACTION_CONTROLLER_URL}
CMD graphql-engine \
    --database-url $HASURA_GRAPHQL_DATABASE_URL \
    serve \
    --server-port 9691
